---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 14 天免费试用期结束后，有两种方式可以支付同步关系的费用。第一个选择是现收现付。第二种选择是直接从NetApp购买许可证。 
---
= NetApp Copy and Sync 免费试用期结束后，支付同步关系费用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Copy and Sync 的 14 天免费试用期结束后，有两种方式可以支付同步关系的费用。第一个选项是从 AWS 或 Azure 订阅，按使用量付费或按年付费。第二种选择是直接从NetApp购买许可证。

您可以从 AWS Marketplace 或 Azure Marketplace 订阅。您不能同时订阅两者。

您可以选择通过市场订阅使用NetApp的许可证。例如，如果您有 25 个同步关系，则可以使用许可证支付前 20 个同步关系的费用，然后使用剩余的 5 个同步关系从 AWS 或 Azure 按使用量付费。

link:concept-licensing.html["详细了解许可证的运作方式"] 。

如果您在免费试用期结束后没有立即付款，您将无法建立任何其他关系。现有的关系不会被删除，但在您订阅或输入许可证之前，您不能对其进行任何更改。

许可证应通过NetApp Copy and Sync 或适用网站进行管理，而不是通过NetApp Console 订阅进行管理。



== [[aws]]从 AWS 订阅

AWS 允许您按使用量付费或按年付费。

.即用即付的步骤
. 从NetApp控制台导航菜单中，选择 *Mobility > Copy and Sync*。
. 选择*许可*。
. 选择 *AWS*。
. 选择*订阅*，然后选择*继续*。
. 从 AWS Marketplace 订阅，然后重新登录 Copy and Sync 完成注册。
+
以下视频展示了该过程：

+
.从 AWS Marketplace 订阅复制和同步
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.每年付款的步骤
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["转到 AWS Marketplace 页面"^] 。
. 选择*继续订阅*。
. 选择您的合同选项，然后选择*创建合同*。




== [[azure]]从 Azure 订阅

Azure 允许您按使用量付费或按年付费。

.你需要什么
在相关订阅中具有贡献者或所有者权限的 Azure 用户帐户。

.步骤
. 从NetApp控制台导航菜单中，选择 *Mobility > Copy and Sync*。
. 选择*许可*。
. 选择“*Azure*”。
. 选择*订阅*，然后选择*继续*。
. 在 Azure 门户中，选择“*创建*”，选择您的选项，然后选择“*订阅*”。
+
选择“每月”按小时付费，或选择“每年”预付一年的费用。

. 部署完成后，在通知弹出窗口中选择 SaaS 资源的名称。
. 选择“配置帐户”返回“复制和同步”。
+
以下视频展示了该过程：

+
.从 Azure 市场订阅复制和同步
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[licenses]]从NetApp购买许可证并将其添加到复制和同步

要预先支付同步关系的费用，您必须购买一个或多个许可证并将其添加到复制和同步中。

.你需要什么
您需要许可证的序列号以及与该许可证关联的NetApp支持站点帐户的用户名和密码。

.步骤
. 通过 mailto:ng-cloudsync-contact@netapp.com?subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Purchase%20Request[联系NetApp] 购买许可证。
. link:task-login-copyandsync.html["登录以复制和同步"] 。
. 选择*许可*。
. 选择*添加许可证*并添加所需信息：
+
.. 输入序列号。
.. 选择与您要添加的许可证关联的NetApp支持站点帐户：
+
*** 如果您的帐户已添加到NetApp控制台，请从下拉列表中选择它。
*** 如果您的帐户尚未添加，请选择*添加 NSS 凭据*，输入用户名和密码，选择*注册*，然后从下拉列表中选择它。


.. 选择“*添加*”。






== 更新许可证

如果您延长了从NetApp购买的复制和同步许可证，则新的到期日期将不会在复制和同步中自动更新。您需要重新添加许可证以刷新到期日期。许可证应通过复制和同步或适用的网站进行管理，而不是通过NetApp控制台订阅进行管理。

.步骤
. 从NetApp控制台导航菜单中，选择 *Mobility > Copy and Sync*。
. 选择*许可*。
. 选择*添加许可证*并添加所需信息：
+
.. 输入序列号。
.. 选择与您要添加的许可证关联的NetApp支持站点帐户。
.. 选择“*添加*”。




.结果
复制和同步会使用新的到期日期更新现有许可证。
